import React, { createContext, useState, useContext, ReactNode } from 'react';

// Types de langues supportées
export type Language = 'fr' | 'en' | 'es';

// Interface pour le contexte de langue
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string; // Fonction de traduction simplifiée
}

// Création du contexte avec des valeurs par défaut
const LanguageContext = createContext<LanguageContextType>({
  language: 'fr',
  setLanguage: () => {},
  t: (key) => key,
});

// Dictionnaires de traduction
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Traductions françaises
    'app.title': 'SafeKey - Gestionnaire de clés API',
    // Traductions pour la section profil
    'settings.sections.profile.title': 'Profil',
    'settings.sections.profile.desc': 'Gérez vos informations personnelles et vos identifiants de connexion.',
    'settings.profile.personalInfo': 'Informations personnelles',
    'settings.profile.personalInfoDesc': 'Consultez et modifiez vos informations personnelles.',
    'settings.profile.email': 'Adresse e-mail',
    'settings.profile.emailUpdateDesc': 'La modification de l\'adresse e-mail nécessite une confirmation par e-mail.',
    'settings.profile.username': 'Nom d\'utilisateur',
    'settings.profile.registrationDate': 'Date d\'inscription',
    'settings.profile.security': 'Sécurité du compte',
    'settings.profile.securityDesc': 'Gérez votre mot de passe et les paramètres de sécurité.',
    'settings.profile.currentPassword': 'Mot de passe actuel',
    'settings.profile.newPassword': 'Nouveau mot de passe',
    'settings.profile.confirmPassword': 'Confirmer le nouveau mot de passe',
    'settings.profile.changePassword': 'Changer de mot de passe',
    'settings.profile.contactPreferences': 'Préférences de contact',
    'settings.profile.emailNotifications': 'Recevoir des notifications par e-mail',
    'settings.profile.marketingEmails': 'Recevoir des e-mails marketing et des mises à jour',
    'settings.update': 'Mettre à jour',
    'settings.save': 'Enregistrer',
    // Messages toast
    'toast.error.validation': 'Erreur de validation',
    'toast.error.update': 'Erreur de mise à jour',
    'toast.success.update': 'Mise à jour réussie',
    'toast.success.request': 'Demande envoyée',
    'toast.error.emptyEmail': 'L\'adresse e-mail ne peut pas être vide',
    'toast.error.invalidEmail': 'Format d\'adresse e-mail invalide',
    'toast.success.emailSent': 'Un e-mail de confirmation a été envoyé à votre nouvelle adresse.',
    'toast.success.checkInbox': 'Veuillez vérifier votre boîte de réception.',
    'toast.error.emailUpdate': 'Erreur lors de la mise à jour de l\'adresse e-mail',
    'toast.error.emptyUsername': 'Le nom d\'utilisateur ne peut pas être vide',
    'toast.success.usernameUpdate': 'Nom d\'utilisateur mis à jour avec succès',
    'toast.error.usernameUpdate': 'Erreur lors de la mise à jour du nom d\'utilisateur',
    'toast.error.requiredFields': 'Tous les champs sont obligatoires',
    'toast.error.passwordMismatch': 'Les nouveaux mots de passe ne correspondent pas',
    'toast.error.passwordLength': 'Le nouveau mot de passe doit contenir au moins 8 caractères',
    'toast.success.passwordUpdate': 'Mot de passe mis à jour avec succès',
    'toast.error.passwordUpdate': 'Erreur lors de la mise à jour du mot de passe',
    // Anciennes clés supprimées car remplacées par le nouveau format (newKey.*):
    'validation.keyExists': 'Une clé avec ce nom existe déjà',
    'validation.useOtherName': 'Veuillez utiliser un nom différent',
    'validation.validatingKey': 'Vérification de la clé...',
    'validation.validKey': 'Clé OpenAI valide',
    'validation.invalidKey': 'Clé OpenAI invalide ou expirée',
    'validation.error': 'Erreur lors de la vérification',
    'settings.language': 'Langue et région',
    'settings.languageDescription': 'Changer la langue et la région modifiera tous les textes de l\'interface',
    'settings.french': 'Français (France)',
    'settings.english': 'Anglais (États-Unis)',
    'settings.spanish': 'Espagnol (Espagne)',
    'sidebar.newKey': 'Nouvelle clé',
    'sidebar.dashboard': 'Tableau de bord',
    'sidebar.projects': 'Mes projets',
    'sidebar.history': 'Historique',
    'sidebar.settings': 'Paramètres',
    // Clé supprimée car remplacée par sidebar.recentProjects
    'sidebar.footer': 'Version',
    'sidebar.theme': 'Thème',
    'sidebar.logout': 'Déconnexion',
    
    'settings.title': 'Paramètres',
    'settings.appearance': 'Apparence',
    'settings.darkMode': 'Mode sombre',
    'settings.security': 'Sécurité',
    'settings.expirationThreshold': 'Seuil d\'expiration',
    'settings.expirationThresholdDesc': 'Définir le nombre de jours avant d\'\u00eatre notifié de l\'expiration d\'une clé',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Notifications par email',
    'settings.emailNotificationsDesc': 'Recevoir des notifications par email pour les événements importants',
    'settings.pushNotifications': 'Notifications push',
    'settings.pushNotificationsDesc': 'Recevoir des notifications push pour les événements importants',
    'settings.history': 'Historique',
    'settings.clearHistory': 'Effacer l\'historique',
    'settings.clearHistoryDesc': 'Supprimer définitivement tout l\'historique des actions',
    'settings.clearHistoryConfirm': 'Êtes-vous sûr de vouloir effacer tout l\'historique ?',
    'settings.clearHistoryWarning': 'Cette action est irréversible',
    'settings.cancel': 'Annuler',
    'settings.confirm': 'Confirmer',
    'settings.twoFactorAuth': 'l\'authentification à deux facteurs',
    'settings.hideApiKeys': 'Masquer les clés API par défaut',
    'settings.enableNotifications': 'Activer les notifications',
    'settings.notifyExpiration': 'Notifications d\'expiration de clé',
    'settings.notifyNewKey': 'Notifications de modification de clé',
    'settings.notifyLogin': 'Notifications de tentative d\'accès',
    'settings.export': 'Exportation',
    'settings.exportKeys': 'Exporter les clés',
    'settings.exportKeysDesc': 'Exporter toutes les clés API au format CSV ou JSON',
    'settings.exportAsCSV': 'Exporter en CSV',
    'settings.exportAsJSON': 'Exporter en JSON',
    'settings.exportHistory': 'Exporter l\'historique',
    'settings.exportHistoryDesc': 'Exporter l\'historique des actions au format JSON',
    
    'settings.sections.general.title': 'Général',
    'settings.sections.general.desc': 'Paramètres généraux de l\'application',
    'settings.sections.security.title': 'Sécurité',
    'settings.sections.security.desc': 'Paramètres de sécurité et de confidentialité',
    'settings.sections.notifications.title': 'Notifications',
    'settings.sections.notifications.desc': 'Gérer les notifications et les alertes',
    'settings.sections.history.title': 'Historique',
    'settings.sections.history.desc': 'Gérer l\'historique des actions',
    'settings.sections.export.title': 'Exportation',
    'settings.sections.export.desc': 'Exporter les clés API',
    
    'dashboard.title': 'Tableau de bord',
    'dashboard.overview': 'Aperçu',
    'dashboard.activeKeys': 'Clés actives',
    'dashboard.expiringSoon': 'Clés expirant bientôt',
    'dashboard.projects': 'Projets',
    'dashboard.search': 'Rechercher...',
    'dashboard.filter': 'Filtrer',
    'dashboard.filterBy': 'Filtrer par',
    // Propriété déjà définie plus haut
    'dashboard.tags': 'Tags',
    'dashboard.expiration': 'Expiration',
    'dashboard.expired': 'Expirée',
    'dashboard.lessThanThreshold': 'Expire < {days} jours',
    'dashboard.moreThanThreshold': 'Expire > {days} jours',
    'dashboard.clearFilters': 'Effacer les filtres',
    'dashboard.apply': 'Appliquer',
    'dashboard.noResults': 'Aucun résultat trouvé',
    'dashboard.noProjects': 'Aucun projet disponible',
    'dashboard.loadingKeys': 'Chargement des clés...',
    'dashboard.addNewKey': 'Ajouter une nouvelle clé',
    'dashboard.defaultProject': 'Projet par défaut',
    'dashboard.pagination': 'Page {current} sur {total}',
    'dashboard.expiresSoon': 'Expire bientôt',
    'dashboard.active': 'Active',
    'dashboard.name': 'Nom',
    'dashboard.apiKey': 'Clé API',
    'dashboard.actions': 'Actions',
    'dashboard.expiresIn': 'Expire dans {days} jours',
    'dashboard.previous': 'Précédent',
    'dashboard.next': 'Suivant',
    'dashboard.defaultProjectName': 'Projet par défaut',
    'dashboard.edit': 'Modifier',
    'dashboard.delete': 'Supprimer',
    'dashboard.copy': 'Copier',
    'dashboard.view': 'Voir',
    'dashboard.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette clé ?',
    'dashboard.keyCopied': 'Clé copiée dans le presse-papiers',
    'dashboard.keyDeleted': 'Clé API supprimée',
    'dashboard.keyDeletedDesc': 'La clé a été supprimée avec succès.',
    'dashboard.keyUpdated': 'Clé API modifiée avec succès',
    'dashboard.loadingError': 'Erreur lors du chargement des projets',
    'dashboard.confirmDeleteMessage': 'Êtes-vous sûr de vouloir supprimer cette clé API ? Cette action est irréversible.',
    'dashboard.keyDetails': 'Détails de la clé API',
    'dashboard.expirationStatus': 'Statut d\'expiration',
    'dashboard.editKey': 'Modifier la clé API',
    'common.cancel': 'Annuler',
    'dashboard.unknownProject': 'Projet inconnu',
    'dashboard.copyError': 'Erreur lors de la copie de la clé',
    'dashboard.updateError': 'Erreur lors de la modification de la clé',
    
    'projects.title': 'Mes projets',
    'projects.newProject': 'Nouveau projet',
    'projects.noProjects': 'Aucun projet',
    'projects.noProjectsDesc': 'Commencez par créer un nouveau projet pour organiser vos clés API.',
    'projects.modified': 'Modifié le',
    'projects.keys': 'clé',
    'projects.keysPlural': 'clés',
    'projects.active': 'Actif',
    'projects.edit': 'Modifier',
    'projects.archive': 'Archiver',
    'projects.noDescription': 'Aucune description',
    'projects.activeKeys': 'active',
    'projects.activeKeysPlural': 'actives',
    'projects.name': 'Nom',
    'projects.key': 'Clé',
    'projects.environment': 'Environnement',
    'projects.expiration': 'Expiration',
    'projects.provider': 'Fournisseur',
    'projects.noExpiration': 'Pas d\'expiration',
    'projects.keyCopied': 'Clé copiée dans le presse-papier',
    'projects.createNew': 'Nouveau projet',
    'projects.projectName': 'Nom du projet *',
    'projects.description': 'Description',
    'projects.cancel': 'Annuler',
    'projects.create': 'Créer',
    'projects.editProject': 'Modifier le projet',
    'projects.save': 'Enregistrer',
    'projects.confirmDelete': 'Confirmer l\'archivage',
    'projects.confirmDeleteDesc': 'Êtes-vous sûr de vouloir archiver ce projet ? Les clés API associées resteront accessibles.',
    'projects.deleteProject': 'Archiver le projet',
    'projects.confirmDeleteDesc2': 'Cette action est irréversible.',
    'projects.confirmArchive': 'Archiver',
    'projects.createSuccess': 'Projet "{name}" créé avec succès',
    'projects.updateSuccess': 'Projet "{name}" modifié avec succès',
    'projects.archiveSuccess': 'Projet archivé avec succès',
    'projects.loadingError': 'Erreur lors du chargement des projets',
    'projects.keysLoadingError': 'Erreur lors du chargement des clés',
    'projects.createError': 'Erreur lors de la création du projet',
    'projects.updateError': 'Erreur lors de la modification du projet',
    'projects.archiveError': 'Erreur lors de l\'archivage du projet',
    'projects.environmentProduction': 'Production',
    'projects.environmentStaging': 'Test',
    'projects.environmentDevelopment': 'Développement',
    
    'newKey.title': 'Nouvelle clé API',
    'newKey.name': 'Nom de la clé *',
    'newKey.namePlaceholder': 'ex: API OpenAI Production',
    'newKey.value': 'Valeur de la clé *',
    'newKey.valuePlaceholder': 'ex: sk_...',
    'newKey.validating': 'Vérification de la clé...',
    'newKey.openaiExpiration': 'Les clés OpenAI expirent automatiquement après 3 mois',
    'newKey.project': 'Projet',
    'newKey.selectProject': 'Sélectionner un projet',
    'newKey.newProject': '+ Nouveau projet',
    'newKey.newProjectName': 'Nom du nouveau projet *',
    'newKey.newProjectPlaceholder': 'ex: Site e-commerce',
    'newKey.environment': 'Environnement',
    'newKey.selectEnvironment': 'Sélectionner un type',
    'newKey.production': 'Production',
    'newKey.development': 'Développement',
    'newKey.staging': 'Test',
    'newKey.environmentReadOnly': 'Le type de clé est défini par le projet sélectionné',
    'newKey.category': 'Catégorie de projet',
    'newKey.selectCategory': 'Sélectionner un type',
    'newKey.ecommerce': 'Site e-commerce',
    'newKey.internalApi': 'API interne',
    'newKey.mobileApp': 'Application mobile',
    'newKey.misc': 'Divers',
    'newKey.cancel': 'Annuler',
    'newKey.create': 'Créer',
    'newKey.duplicateError': 'Nom de clé déjà utilisé',
    'newKey.duplicateErrorDesc': 'Une clé avec le nom "{name}" existe déjà. Veuillez utiliser un nom différent.',
    'newKey.createError': 'Erreur de création',
    'newKey.createErrorDesc': 'Une erreur est survenue lors de la création de la clé API.',
    'newKey.loadingError': 'Erreur lors du chargement des projets',
    'newKey.validKey': 'Clé OpenAI valide',
    'newKey.validKeyDesc': 'La clé API a été validée avec succès.',
    'newKey.invalidKey': 'Clé OpenAI invalide ou expirée',
    'newKey.invalidKeyDesc': 'La clé API fournie est invalide ou a expiré.',
    'newKey.validationError': 'Erreur de validation',
    'newKey.validationErrorDesc': 'Impossible de vérifier la clé API. Veuillez réessayer.',
    'newKey.noProject': 'Sans projet',
    
    'sidebar.recentProjects': 'NOUVEAUX PROJETS',
    'sidebar.projectEcommerce': 'Site e-commerce',
    'sidebar.projectInternalApi': 'API interne',
    'sidebar.projectMobileApp': 'Application mobile',
    'sidebar.lightMode': 'Mode clair',
    'sidebar.darkMode': 'Mode sombre',
    
    // Les traductions de la modale d'édition de projet sont déjà définies plus haut
    
    // Page d'historique
    'history.title': 'Historique des actions',
    'history.date': 'Date',
    'history.action': 'Action',
    'history.project': 'Projet',
    'history.environment': 'Environnement',
    'history.details': 'Détails',
    'history.defaultProject': 'Projet par défaut',
    'history.loading': 'Chargement de l\'historique...',
    'history.action.created': 'Création',
    'history.action.updated': 'Modification',
    'history.action.deleted': 'Suppression',
    'history.action.viewed': 'Consultation',
    'history.action.rotated': 'Rotation',
    'history.details.created': 'Nouvelle clé API créée pour {project}',
    'history.details.updated': 'Clé API modifiée',
    'history.details.deleted': 'Clé API supprimée',
    'history.details.viewed': 'Clé API consultée',
    'history.details.rotated': 'Clé API renouvelée',
    'history.details.nameChanged': 'nom modifié de "{old}" à "{new}"',
    'history.details.environmentChanged': 'environnement modifié de "{old}" à "{new}"',
    'history.details.statusChanged': 'statut modifié à {status}',
    'history.details.active': 'actif',
    'history.details.inactive': 'inactif',
    'history.environment.production': 'Production',
    'history.environment.staging': 'Test',
    'history.environment.development': 'Développement',
    
    // Settings page
    'settings.clearHistorySuccess': 'Historique effacé avec succès',
    'settings.clearHistoryError': 'Erreur lors de l\'effacement de l\'historique',
  },
  en: {
    // Traductions anglaises
    'app.title': 'SafeKey - API Key Manager',
    // Traductions pour la section profil
    'settings.sections.profile.title': 'Profile',
    'settings.sections.profile.desc': 'Manage your personal information and login credentials.',
    'settings.profile.personalInfo': 'Personal Information',
    'settings.profile.personalInfoDesc': 'View and edit your personal information.',
    'settings.profile.email': 'Email address',
    'settings.profile.emailUpdateDesc': 'Changing your email address requires email confirmation.',
    'settings.profile.username': 'Username',
    'settings.profile.registrationDate': 'Registration date',
    'settings.profile.security': 'Account Security',
    'settings.profile.securityDesc': 'Manage your password and security settings.',
    'settings.profile.currentPassword': 'Current password',
    'settings.profile.newPassword': 'New password',
    'settings.profile.confirmPassword': 'Confirm new password',
    'settings.profile.changePassword': 'Change password',
    'settings.profile.contactPreferences': 'Contact Preferences',
    'settings.profile.emailNotifications': 'Receive email notifications',
    'settings.profile.marketingEmails': 'Receive marketing emails and updates',
    'settings.update': 'Update',
    'settings.save': 'Save',
    // Toast messages
    'toast.error.validation': 'Validation Error',
    'toast.error.update': 'Update Error',
    'toast.success.update': 'Update Successful',
    'toast.success.request': 'Request Sent',
    'toast.error.emptyEmail': 'Email address cannot be empty',
    'toast.error.invalidEmail': 'Invalid email format',
    'toast.success.emailSent': 'A confirmation email has been sent to your new address.',
    'toast.success.checkInbox': 'Please check your inbox.',
    'toast.error.emailUpdate': 'Error updating email address',
    'toast.error.emptyUsername': 'Username cannot be empty',
    'toast.success.usernameUpdate': 'Username successfully updated',
    'toast.error.usernameUpdate': 'Error updating username',
    'toast.error.requiredFields': 'All fields are required',
    'toast.error.passwordMismatch': 'New passwords do not match',
    'toast.error.passwordLength': 'New password must be at least 8 characters long',
    'toast.success.passwordUpdate': 'Password successfully updated',
    'toast.error.passwordUpdate': 'Error updating password',
    'validation.keyExists': 'A key with this name already exists',
    'validation.useOtherName': 'Please use a different name',
    'validation.validatingKey': 'Validating key...',
    'validation.validKey': 'Valid OpenAI key',
    'validation.invalidKey': 'Invalid or expired OpenAI key',
    'validation.error': 'Error during validation',
    'settings.language': 'Language and Region',
    'settings.languageDescription': 'Changing the language and region will update all interface texts',
    'settings.french': 'French (France)',
    'settings.english': 'English (United States)',
    'settings.spanish': 'Spanish (Spain)',
    'sidebar.newKey': 'New key',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.projects': 'My projects',
    'sidebar.history': 'History',
    'sidebar.settings': 'Settings',
    // Clé supprimée car remplacée par sidebar.recentProjects
    'sidebar.footer': 'Version',
    'sidebar.theme': 'Theme',
    'sidebar.logout': 'Logout',
    
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark mode',
    'settings.security': 'Security',
    'settings.expirationThreshold': 'Expiration threshold',
    'settings.expirationThresholdDesc': 'Set the number of days before being notified of key expiration',
    'settings.notifications': 'Notifications',
    'settings.emailNotifications': 'Email notifications',
    'settings.emailNotificationsDesc': 'Receive email notifications for important events',
    'settings.pushNotifications': 'Push notifications',
    'settings.pushNotificationsDesc': 'Receive push notifications for important events',
    'settings.history': 'History',
    'settings.clearHistory': 'Clear history',
    'settings.clearHistoryDesc': 'Permanently delete all action history',
    'settings.clearHistoryConfirm': 'Are you sure you want to clear all history?',
    'settings.clearHistoryWarning': 'This action cannot be undone',
    'settings.cancel': 'Cancel',
    'settings.confirm': 'Confirm',
    'settings.twoFactorAuth': 'two-factor authentication',
    'settings.hideApiKeys': 'Hide API keys by default',
    'settings.enableNotifications': 'Enable notifications',
    'settings.notifyExpiration': 'Key expiration notifications',
    'settings.notifyNewKey': 'Key modification notifications',
    'settings.notifyLogin': 'Login attempt notifications',
    'settings.export': 'Export',
    'settings.exportKeys': 'Export keys',
    'settings.exportKeysDesc': 'Export all API keys in CSV or JSON format',
    'settings.exportAsCSV': 'Export as CSV',
    'settings.exportAsJSON': 'Export as JSON',
    'settings.exportHistory': 'Export history',
    'settings.exportHistoryDesc': 'Export action history in JSON format',
    
    'settings.sections.general.title': 'General',
    'settings.sections.general.desc': 'General application settings',
    'settings.sections.security.title': 'Security',
    'settings.sections.security.desc': 'Security and privacy settings',
    'settings.sections.notifications.title': 'Notifications',
    'settings.sections.notifications.desc': 'Manage notifications and alerts',
    'settings.sections.history.title': 'History',
    'settings.sections.history.desc': 'Manage action history',
    'settings.sections.export.title': 'Export',
    'settings.sections.export.desc': 'Export API keys',
    
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.activeKeys': 'Active Keys',
    'dashboard.expiringSoon': 'Keys Expiring Soon',
    'dashboard.projects': 'Projects',
    'dashboard.search': 'Search...',
    'dashboard.filter': 'Filter',
    'dashboard.filterBy': 'Filter by',
    // Property already defined above
    'dashboard.tags': 'Tags',
    'dashboard.expiration': 'Expiration',
    'dashboard.expired': 'Expired',
    'dashboard.lessThanThreshold': 'Expires < {days} days',
    'dashboard.moreThanThreshold': 'Expires > {days} days',
    'dashboard.clearFilters': 'Clear filters',
    'dashboard.apply': 'Apply',
    'dashboard.noResults': 'No results found',
    'dashboard.noProjects': 'No projects available',
    'dashboard.loadingKeys': 'Loading keys...',
    'dashboard.addNewKey': 'Add New Key',
    'dashboard.defaultProject': 'Default Project',
    'dashboard.pagination': 'Page {current} of {total}',
    'dashboard.expiresSoon': 'Expires soon',
    'dashboard.active': 'Active',
    'dashboard.name': 'Name',
    'dashboard.apiKey': 'API Key',
    // Property already defined above
    'dashboard.actions': 'Actions',
    'dashboard.expiresIn': 'Expires in {days} days',
    'dashboard.previous': 'Previous',
    'dashboard.next': 'Next',
    'dashboard.defaultProjectName': 'Default Project',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Delete',
    'dashboard.copy': 'Copy',
    'dashboard.view': 'View',
    'dashboard.confirmDelete': 'Are you sure you want to delete this key?',
    'dashboard.keyCopied': 'Key copied to clipboard',
    'dashboard.keyDeleted': 'API Key deleted',
    'dashboard.keyDeletedDesc': 'The key has been successfully deleted.',
    'dashboard.keyUpdated': 'API Key successfully updated',
    'dashboard.loadingError': 'Error loading projects',
    'dashboard.confirmDeleteMessage': 'Are you sure you want to delete this API key? This action cannot be undone.',
    'dashboard.keyDetails': 'API Key Details',
    'dashboard.expirationStatus': 'Expiration Status',
    'dashboard.editKey': 'Edit API Key',
    'common.cancel': 'Cancel',
    'dashboard.unknownProject': 'Unknown project',
    'dashboard.copyError': 'Error copying the key',
    'dashboard.updateError': 'Error updating the key',
    
    'projects.title': 'My projects',
    'projects.newProject': 'New project',
    'projects.noProjects': 'No projects',
    'projects.noProjectsDesc': 'Start by creating a new project to organize your API keys.',
    'projects.modified': 'Modified on',
    'projects.keys': 'key',
    'projects.keysPlural': 'keys',
    'projects.active': 'Active',
    'projects.edit': 'Edit',
    'projects.archive': 'Archive',
    'projects.noDescription': 'No description',
    'projects.activeKeys': 'active',
    'projects.activeKeysPlural': 'active',
    'projects.name': 'Name',
    'projects.key': 'Key',
    'projects.environment': 'Environment',
    'projects.expiration': 'Expiration',
    'projects.provider': 'Provider',
    'projects.noExpiration': 'No expiration',
    'projects.keyCopied': 'Key copied to clipboard',
    'projects.createNew': 'New project',
    'projects.projectName': 'Project name *',
    'projects.description': 'Description',
    'projects.cancel': 'Cancel',
    'projects.create': 'Create',
    'projects.editProject': 'Edit project',
    'projects.save': 'Save',
    'projects.confirmDelete': 'Confirm archiving',
    'projects.confirmDeleteDesc': 'Are you sure you want to archive this project? Associated API keys will remain accessible.',
    'projects.deleteProject': 'Archive project',
    'projects.confirmDeleteDesc2': 'This action cannot be undone.',
    'projects.confirmArchive': 'Archive',
    'projects.createSuccess': 'Project "{name}" created successfully',
    'projects.updateSuccess': 'Project "{name}" updated successfully',
    'projects.archiveSuccess': 'Project archived successfully',
    'projects.loadingError': 'Error loading projects',
    'projects.keysLoadingError': 'Error loading keys',
    'projects.createError': 'Error creating project',
    'projects.updateError': 'Error updating project',
    'projects.archiveError': 'Error archiving project',
    'projects.environmentProduction': 'Production',
    'projects.environmentStaging': 'Staging',
    'projects.environmentDevelopment': 'Development',
    
    'newKey.title': 'New API Key',
    'newKey.name': 'Key name *',
    'newKey.namePlaceholder': 'e.g.: OpenAI Production API',
    'newKey.value': 'Key value *',
    'newKey.valuePlaceholder': 'e.g.: sk_...',
    'newKey.validating': 'Validating key...',
    'newKey.openaiExpiration': 'OpenAI keys automatically expire after 3 months',
    'newKey.project': 'Project',
    'newKey.selectProject': 'Select a project',
    'newKey.newProject': '+ New project',
    'newKey.newProjectName': 'New project name *',
    'newKey.newProjectPlaceholder': 'e.g.: E-commerce website',
    'newKey.environment': 'Environment',
    'newKey.selectEnvironment': 'Select a type',
    'newKey.production': 'Production',
    'newKey.development': 'Development',
    'newKey.staging': 'Staging',
    'newKey.environmentReadOnly': 'The key type is defined by the selected project',
    'newKey.category': 'Project category',
    'newKey.selectCategory': 'Select a type',
    'newKey.ecommerce': 'E-commerce website',
    'newKey.internalApi': 'Internal API',
    'newKey.mobileApp': 'Mobile application',
    'newKey.misc': 'Miscellaneous',
    'newKey.cancel': 'Cancel',
    'newKey.create': 'Create',
    'newKey.duplicateError': 'Key name already in use',
    'newKey.duplicateErrorDesc': 'A key with the name "{name}" already exists. Please use a different name.',
    'newKey.createError': 'Creation error',
    'newKey.createErrorDesc': 'An error occurred while creating the API key.',
    'newKey.loadingError': 'Error loading projects',
    'newKey.validKey': 'Valid OpenAI key',
    'newKey.validKeyDesc': 'The API key has been successfully validated.',
    'newKey.invalidKey': 'Invalid or expired OpenAI key',
    'newKey.invalidKeyDesc': 'The provided API key is invalid or has expired.',
    'newKey.validationError': 'Validation error',
    'newKey.validationErrorDesc': 'Unable to verify the API key. Please try again.',
    'newKey.noProject': 'No project',
    
    'sidebar.recentProjects': 'NEW PROJECTS',
    'sidebar.projectEcommerce': 'E-commerce website',
    'sidebar.projectInternalApi': 'Internal API',
    'sidebar.projectMobileApp': 'Mobile application',
    'sidebar.lightMode': 'Light mode',
    'sidebar.darkMode': 'Dark mode',
    
    // Edit project modal translations are already defined above
    
    // History page
    'history.title': 'Action History',
    'history.date': 'Date',
    'history.action': 'Action',
    'history.project': 'Project',
    'history.environment': 'Environment',
    'history.details': 'Details',
    'history.defaultProject': 'Default project',
    'history.loading': 'Loading history...',
    'history.action.created': 'Created',
    'history.action.updated': 'Updated',
    'history.action.deleted': 'Deleted',
    'history.action.viewed': 'Viewed',
    'history.action.rotated': 'Rotated',
    'history.details.created': 'New API key created for {project}',
    'history.details.updated': 'API key updated',
    'history.details.deleted': 'API key deleted',
    'history.details.viewed': 'API key viewed',
    'history.details.rotated': 'API key rotated',
    'history.details.nameChanged': 'name changed from "{old}" to "{new}"',
    'history.details.environmentChanged': 'environment changed from "{old}" to "{new}"',
    'history.details.statusChanged': 'status changed to {status}',
    'history.details.active': 'active',
    'history.details.inactive': 'inactive',
    'history.environment.production': 'Production',
    'history.environment.staging': 'Staging',
    'history.environment.development': 'Development',
    
    // Settings page
    'settings.clearHistorySuccess': 'History cleared successfully',
    'settings.clearHistoryError': 'Error clearing history',
  },
  es: {
    // Traductions espagnoles
    'app.title': 'SafeKey - Gestor de Claves API',
    // Traductions pour la section profil
    'settings.sections.profile.title': 'Perfil',
    'settings.sections.profile.desc': 'Gestione su información personal y credenciales de inicio de sesión.',
    'settings.profile.personalInfo': 'Información personal',
    'settings.profile.personalInfoDesc': 'Consulte y modifique su información personal.',
    'settings.profile.email': 'Dirección de correo electrónico',
    'settings.profile.emailUpdateDesc': 'La modificación de la dirección de correo electrónico requiere confirmación por correo electrónico.',
    'settings.profile.username': 'Nombre de usuario',
    'settings.profile.registrationDate': 'Fecha de registro',
    'settings.profile.security': 'Seguridad de la cuenta',
    'settings.profile.securityDesc': 'Gestione su contraseña y configuración de seguridad.',
    'settings.profile.currentPassword': 'Contraseña actual',
    'settings.profile.newPassword': 'Nueva contraseña',
    'settings.profile.confirmPassword': 'Confirmar nueva contraseña',
    'settings.profile.changePassword': 'Cambiar contraseña',
    'settings.profile.contactPreferences': 'Preferencias de contacto',
    'settings.profile.emailNotifications': 'Recibir notificaciones por correo electrónico',
    'settings.profile.marketingEmails': 'Recibir correos electrónicos de marketing y actualizaciones',
    'settings.update': 'Actualizar',
    'settings.save': 'Guardar',
    // Mensajes toast
    'toast.error.validation': 'Error de validación',
    'toast.error.update': 'Error de actualización',
    'toast.success.update': 'Actualización exitosa',
    'toast.success.request': 'Solicitud enviada',
    'toast.error.emptyEmail': 'La dirección de correo electrónico no puede estar vacía',
    'toast.error.invalidEmail': 'Formato de correo electrónico inválido',
    'toast.success.emailSent': 'Se ha enviado un correo electrónico de confirmación a su nueva dirección.',
    'toast.success.checkInbox': 'Por favor, revise su bandeja de entrada.',
    'toast.error.emailUpdate': 'Error al actualizar la dirección de correo electrónico',
    'toast.error.emptyUsername': 'El nombre de usuario no puede estar vacío',
    'toast.success.usernameUpdate': 'Nombre de usuario actualizado con éxito',
    'toast.error.usernameUpdate': 'Error al actualizar el nombre de usuario',
    'toast.error.requiredFields': 'Todos los campos son obligatorios',
    'toast.error.passwordMismatch': 'Las nuevas contraseñas no coinciden',
    'toast.error.passwordLength': 'La nueva contraseña debe tener al menos 8 caracteres',
    'toast.success.passwordUpdate': 'Contraseña actualizada con éxito',
    'toast.error.passwordUpdate': 'Error al actualizar la contraseña',
    // Anciennes clés supprimées car remplacées par le nouveau format (newKey.*):
    'validation.keyExists': 'Ya existe una clave con este nombre',
    'validation.useOtherName': 'Por favor, utilice un nombre diferente',
    'validation.validatingKey': 'Validando clave...',
    'validation.validKey': 'Clave OpenAI válida',
    'validation.invalidKey': 'Clave OpenAI inválida o caducada',
    'validation.error': 'Error durante la validación',
    'settings.language': 'Idioma',
    'settings.languageDescription': 'Cambiar el idioma actualizará todos los textos de la interfaz',
    'settings.french': 'Francés',
    'settings.english': 'Inglés',
    'settings.spanish': 'Español',
    'sidebar.newKey': 'Nueva clave',
    'sidebar.dashboard': 'Panel de control',
    'sidebar.projects': 'Mis proyectos',
    'sidebar.history': 'Historial',
    'sidebar.settings': 'Ajustes',
    // Clé supprimée car remplacée par sidebar.recentProjects
    'sidebar.footer': 'Versión',
    'sidebar.theme': 'Tema',
    'sidebar.logout': 'Cerrar sesión',
    
    'settings.title': 'Ajustes',
    'settings.appearance': 'Apariencia',
    'settings.darkMode': 'Modo oscuro',
    'settings.security': 'Seguridad',
    'settings.expirationThreshold': 'Umbral de caducidad',
    'settings.expirationThresholdDesc': 'Establecer el número de días antes de ser notificado de la caducidad de la clave',
    'settings.notifications': 'Notificaciones',
    'settings.emailNotifications': 'Notificaciones por correo electrónico',
    'settings.emailNotificationsDesc': 'Recibir notificaciones por correo electrónico para eventos importantes',
    'settings.pushNotifications': 'Notificaciones push',
    'settings.pushNotificationsDesc': 'Recibir notificaciones push para eventos importantes',
    'settings.history': 'Historial',
    'settings.clearHistory': 'Borrar historial',
    'settings.clearHistoryDesc': 'Eliminar permanentemente todo el historial de acciones',
    'settings.clearHistoryConfirm': '¿Está seguro de que desea borrar todo el historial?',
    'settings.clearHistoryWarning': 'Esta acción no se puede deshacer',
    'settings.cancel': 'Cancelar',
    'settings.confirm': 'Confirmar',
    'settings.twoFactorAuth': 'la autenticación de dos factores',
    'settings.hideApiKeys': 'Ocultar claves API por defecto',
    'settings.enableNotifications': 'Activar notificaciones',
    'settings.notifyExpiration': 'Notificaciones de caducidad de clave',
    'settings.notifyNewKey': 'Notificaciones de modificación de clave',
    'settings.notifyLogin': 'Notificaciones de intento de acceso',
    'settings.export': 'Exportación',
    'settings.exportKeys': 'Exportar claves',
    'settings.exportKeysDesc': 'Exportar todas las claves API en formato CSV o JSON',
    'settings.exportAsCSV': 'Exportar como CSV',
    'settings.exportAsJSON': 'Exportar como JSON',
    'settings.exportHistory': 'Exportar historial',
    'settings.exportHistoryDesc': 'Exportar historial de acciones en formato JSON',
    
    'settings.sections.general.title': 'General',
    'settings.sections.general.desc': 'Configuración general de la aplicación',
    'settings.sections.security.title': 'Seguridad',
    'settings.sections.security.desc': 'Configuración de seguridad y privacidad',
    'settings.sections.notifications.title': 'Notificaciones',
    'settings.sections.notifications.desc': 'Gestionar notificaciones y alertas',
    'settings.sections.history.title': 'Historial',
    'settings.sections.history.desc': 'Gestionar historial de acciones',
    'settings.sections.export.title': 'Exportación',
    'settings.sections.export.desc': 'Exportar claves API',
    
    'dashboard.title': 'Panel de control',
    'dashboard.overview': 'Resumen',
    'dashboard.activeKeys': 'Claves activas',
    'dashboard.expiringSoon': 'Claves a punto de caducar',
    'dashboard.projects': 'Proyectos',
    'dashboard.search': 'Buscar...',
    'dashboard.filter': 'Filtrar',
    'dashboard.filterBy': 'Filtrar por',
    // Propiedad ya definida arriba
    'dashboard.tags': 'Etiquetas',
    'dashboard.expiration': 'Vencimiento',
    'dashboard.expired': 'Caducadas',
    'dashboard.lessThanThreshold': 'Caduca < {days} días',
    'dashboard.moreThanThreshold': 'Caduca > {days} días',
    'dashboard.clearFilters': 'Borrar filtros',
    'dashboard.apply': 'Aplicar',
    'dashboard.noResults': 'No se encontraron resultados',
    'dashboard.noProjects': 'No hay proyectos disponibles',
    'dashboard.loadingKeys': 'Cargando claves...',
    'dashboard.addNewKey': 'Añadir nueva clave',
    'dashboard.defaultProject': 'Proyecto predeterminado',
    'dashboard.pagination': 'Página {current} de {total}',
    'dashboard.expiresSoon': 'Caduca pronto',
    'dashboard.active': 'Activa',
    'dashboard.name': 'Nombre',
    'dashboard.apiKey': 'Clave API',
    // Propiedad ya definida arriba
    'dashboard.actions': 'Acciones',
    'dashboard.expiresIn': 'Caduca en {days} días',
    'dashboard.previous': 'Anterior',
    'dashboard.next': 'Siguiente',
    'dashboard.defaultProjectName': 'Proyecto predeterminado',
    'dashboard.edit': 'Editar',
    'dashboard.delete': 'Eliminar',
    'dashboard.copy': 'Copiar',
    'dashboard.view': 'Ver',
    'dashboard.confirmDelete': '¿Está seguro de que desea eliminar esta clave?',
    'dashboard.keyCopied': 'Clave copiada al portapapeles',
    'dashboard.keyDeleted': 'Clave API eliminada',
    'dashboard.keyDeletedDesc': 'La clave ha sido eliminada con éxito.',
    'dashboard.keyUpdated': 'Clave API actualizada con éxito',
    'dashboard.loadingError': 'Error al cargar los proyectos',
    'dashboard.confirmDeleteMessage': '¿Está seguro de que desea eliminar esta clave API? Esta acción no se puede deshacer.',
    'dashboard.keyDetails': 'Detalles de la clave API',
    'dashboard.expirationStatus': 'Estado de caducidad',
    'dashboard.editKey': 'Editar clave API',
    'common.cancel': 'Cancelar',
    'dashboard.unknownProject': 'Proyecto desconocido',
    'dashboard.copyError': 'Error al copiar la clave',
    'dashboard.updateError': 'Error al actualizar la clave',
    
    'projects.title': 'Mis proyectos',
    'projects.newProject': 'Nuevo proyecto',
    'projects.noProjects': 'Sin proyectos',
    'projects.noProjectsDesc': 'Comienza creando un nuevo proyecto para organizar tus claves API.',
    'projects.modified': 'Modificado el',
    'projects.keys': 'clave',
    'projects.keysPlural': 'claves',
    'projects.active': 'Activo',
    'projects.edit': 'Editar',
    'projects.archive': 'Archivar',
    'projects.noDescription': 'Sin descripción',
    'projects.activeKeys': 'activa',
    'projects.activeKeysPlural': 'activas',
    'projects.name': 'Nombre',
    'projects.key': 'Clave',
    'projects.environment': 'Entorno',
    'projects.expiration': 'Caducidad',
    'projects.provider': 'Proveedor',
    'projects.noExpiration': 'Sin caducidad',
    'projects.keyCopied': 'Clave copiada al portapapeles',
    'projects.createNew': 'Nuevo proyecto',
    'projects.projectName': 'Nombre del proyecto *',
    'projects.description': 'Descripción',
    'projects.cancel': 'Cancelar',
    'projects.create': 'Crear',
    'projects.editProject': 'Editar proyecto',
    'projects.save': 'Guardar',
    'projects.confirmDelete': 'Confirmar archivo',
    'projects.confirmDeleteDesc': '¿Está seguro de que desea archivar este proyecto? Las claves API asociadas seguirán siendo accesibles.',
    'projects.deleteProject': 'Archivar proyecto',
    'projects.confirmDeleteDesc2': 'Esta acción no se puede deshacer.',
    'projects.confirmArchive': 'Archivar',
    'projects.createSuccess': 'Proyecto "{name}" creado con éxito',
    'projects.updateSuccess': 'Proyecto "{name}" actualizado con éxito',
    'projects.archiveSuccess': 'Proyecto archivado con éxito',
    'projects.loadingError': 'Error al cargar los proyectos',
    'projects.keysLoadingError': 'Error al cargar las claves',
    'projects.createError': 'Error al crear el proyecto',
    'projects.updateError': 'Error al actualizar el proyecto',
    'projects.archiveError': 'Error al archivar el proyecto',
    'projects.environmentProduction': 'Producción',
    'projects.environmentStaging': 'Pruebas',
    'projects.environmentDevelopment': 'Desarrollo',
    
    'newKey.title': 'Nueva clave API',
    'newKey.name': 'Nombre de la clave *',
    'newKey.namePlaceholder': 'ej: API OpenAI Producción',
    'newKey.value': 'Valor de la clave *',
    'newKey.valuePlaceholder': 'ej: sk_...',
    'newKey.validating': 'Verificando clave...',
    'newKey.openaiExpiration': 'Las claves OpenAI caducan automáticamente después de 3 meses',
    'newKey.project': 'Proyecto',
    'newKey.selectProject': 'Seleccionar un proyecto',
    'newKey.newProject': '+ Nuevo proyecto',
    'newKey.newProjectName': 'Nombre del nuevo proyecto *',
    'newKey.newProjectPlaceholder': 'ej: Sitio web de comercio electrónico',
    'newKey.environment': 'Entorno',
    'newKey.selectEnvironment': 'Seleccionar un tipo',
    'newKey.production': 'Producción',
    'newKey.development': 'Desarrollo',
    'newKey.staging': 'Pruebas',
    'newKey.environmentReadOnly': 'El tipo de clave está definido por el proyecto seleccionado',
    'newKey.category': 'Categoría de proyecto',
    'newKey.selectCategory': 'Seleccionar un tipo',
    'newKey.ecommerce': 'Sitio web de comercio electrónico',
    'newKey.internalApi': 'API interna',
    'newKey.mobileApp': 'Aplicación móvil',
    'newKey.misc': 'Varios',
    'newKey.cancel': 'Cancelar',
    'newKey.create': 'Crear',
    'newKey.duplicateError': 'Nombre de clave ya en uso',
    'newKey.duplicateErrorDesc': 'Ya existe una clave con el nombre "{name}". Utilice un nombre diferente.',
    'newKey.createError': 'Error de creación',
    'newKey.createErrorDesc': 'Se produjo un error al crear la clave API.',
    'newKey.loadingError': 'Error al cargar los proyectos',
    'newKey.validKey': 'Clave OpenAI válida',
    'newKey.validKeyDesc': 'La clave API se ha validado correctamente.',
    'newKey.invalidKey': 'Clave OpenAI inválida o caducada',
    'newKey.invalidKeyDesc': 'La clave API proporcionada no es válida o ha caducado.',
    'newKey.validationError': 'Error de validación',
    'newKey.validationErrorDesc': 'No se ha podido verificar la clave API. Inténtelo de nuevo.',
    'newKey.noProject': 'Sin proyecto',
    
    'sidebar.recentProjects': 'NUEVOS PROYECTOS',
    'sidebar.projectEcommerce': 'Sitio e-commerce',
    'sidebar.projectInternalApi': 'API interna',
    'sidebar.projectMobileApp': 'Aplicación móvil',
    'sidebar.lightMode': 'Modo claro',
    'sidebar.darkMode': 'Modo oscuro',
    
    // Las traducciones del modal de edición de proyecto ya están definidas arriba
    
    // Página de historial
    'history.title': 'Historial de acciones',
    'history.date': 'Fecha',
    'history.action': 'Acción',
    'history.project': 'Proyecto',
    'history.environment': 'Entorno',
    'history.details': 'Detalles',
    'history.defaultProject': 'Proyecto predeterminado',
    'history.loading': 'Cargando historial...',
    'history.action.created': 'Creación',
    'history.action.updated': 'Modificación',
    'history.action.deleted': 'Eliminación',
    'history.action.viewed': 'Consulta',
    'history.action.rotated': 'Rotación',
    'history.details.created': 'Nueva clave API creada para {project}',
    'history.details.updated': 'Clave API modificada',
    'history.details.deleted': 'Clave API eliminada',
    'history.details.viewed': 'Clave API consultada',
    'history.details.rotated': 'Clave API renovada',
    'history.details.nameChanged': 'nombre cambiado de "{old}" a "{new}"',
    'history.details.environmentChanged': 'entorno cambiado de "{old}" a "{new}"',
    'history.details.statusChanged': 'estado cambiado a {status}',
    'history.details.active': 'activo',
    'history.details.inactive': 'inactivo',
    'history.environment.production': 'Producción',
    'history.environment.staging': 'Prueba',
    'history.environment.development': 'Desarrollo',
    
    // Página de ajustes
    'settings.clearHistorySuccess': 'Historial borrado con éxito',
    'settings.clearHistoryError': 'Error al borrar el historial',
  },
};

// Fournisseur du contexte de langue
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('fr');

  // Fonction pour changer la langue
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Sauvegarder la préférence de langue dans localStorage
    localStorage.setItem('preferredLanguage', lang);
    // Mettre à jour l'en-tête Accept-Language pour les requêtes API
    document.documentElement.lang = lang;
  };

  // Fonction de traduction
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Initialiser la langue à partir de localStorage au chargement
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language;
    if (savedLanguage && ['fr', 'en', 'es'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
      document.documentElement.lang = savedLanguage;
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personnalisé pour utiliser le contexte de langue
export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
